import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import {
  compareReference,
  reference,
} from '../scripts/reference-comparison.mjs';

test('external fixtures are generated by the checked-in independent solver script', () => {
  const bytes = readFileSync(
    new URL('../scripts/reference-rayoptics.py', import.meta.url),
    'utf8',
  ).replace(/\r\n/g, '\n');
  assert.equal(
    createHash('sha256').update(bytes).digest('hex'),
    reference.generatorSha256,
  );
  assert.equal(reference.packages.rayoptics, '0.9.8');
  assert.equal(reference.cases.length, 10);
  assert.equal(reference.ghosts.length, 3);
});

test('RayOptics exact rays, paraxial focal positions and analytical Fresnel reference matrix', () => {
  const result = compareReference();
  assert.ok(result.checks >= 1000);
  assert.deepEqual(result.failed, []);
});
